version: "3"
services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - type: bind
        source: "./work"
        target: "/work"
    command: start-notebook.sh --NotebookApp.token=''
